#!/bin/sh
#This firewall script was generated by Harvie's php firewall (0.1 Alpha)

#Author: Harvie 2oo7
#Description: Sample HFW Configuration File (THX2 http://www.brandonhutchinson.com/iptables_fw.html)
######################################################################################################


#Rules Others:
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route
echo 1 > /proc/sys/net/ipv4/tcp_syncookies
echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects
echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
echo 1 > /proc/sys/net/ipv4/conf/all/log_martians

#Rules IPTables:
/sbin/iptables --flush

/sbin/iptables -A INPUT -i lo -j ACCEPT
/sbin/iptables -A OUTPUT -o lo -j ACCEPT

/sbin/iptables --policy INPUT DROP
/sbin/iptables --policy OUTPUT DROP
/sbin/iptables --policy FORWARD DROP

/sbin/iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
/sbin/iptables -A OUTPUT -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

/sbin/iptables -A INPUT -p tcp --dport 20 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 21 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 22 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 80 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 8080 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 111 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 113 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 139 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 445 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 548 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 901 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 1023 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 2049 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 5500 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 5900 -m state --state NEW -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 5901 -m state --state NEW -j ACCEPT

/sbin/iptables -A INPUT -j DROP


