#!/bin/bash
#KAlive (<-Harvie 2oo7)
#Use this to prevent ssh timeouting...

SLP=1;
KAM="Keeping alive... ";

clear;
while true; do
	echo -e -n \\r$KAM-;
	sleep $SLP;
	echo -e -n \\r$KAM\\;
        sleep $SLP;
	echo -e -n \\r$KAM\|;
        sleep $SLP;
	echo -e -n \\r$KAM/;
        sleep $SLP;
done;

##EOF

