#!/bin/bash
# -Loads xdxvg support

stop() {
	sleep 3;
	kill -2 "$$" > /dev/null 2>&1;
	kill -9 "$$" > /dev/null 2>&1;
}

echo " []Loading xdxvg support...";
stop &
read;
kill -2 "$!" > /dev/null 2>&1;
kill -9 "$!" > /dev/null 2>&1;
/bin/bash;
